using Indamin.Performance.Data;
using Indamin.Performance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Indamin.Performance.Controllers;
[Authorize(Policy="AdminOnly")]
public class AdminController(AppDbContext db,ExcelService excel):Controller{
public Task<IActionResult>Periods()=>db.Periods.OrderByDescending(x=>x.StartAt).ToListAsync().ContinueWith(t=>(IActionResult)View(t.Result));
[HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>CreatePeriod(string title,string startJalali,string endJalali,string? description){
title=title?.Trim()??"";startJalali=startJalali?.Trim()??"";endJalali=endJalali?.Trim()??"";
if(title==""||startJalali==""||endJalali==""){TempData["Error"]="عنوان و تاریخ‌های شروع و پایان دوره الزامی هستند.";return RedirectToAction(nameof(Periods));}
try{var s=PerformanceService.Jalali(startJalali);var e=PerformanceService.Jalali(endJalali).Date.AddDays(1).AddTicks(-1);if(e<s)TempData["Error"]="تاریخ پایان نمی‌تواند قبل از شروع باشد.";else if(await db.Periods.AnyAsync(x=>x.IsOpen&&s<=x.EndAt&&e>=x.StartAt))TempData["Error"]="بازه این دوره با یک دوره باز دیگر هم‌پوشانی دارد.";else{db.Periods.Add(new EvaluationPeriod{Title=title,StartJalali=PerformanceService.ToJalali(s),EndJalali=PerformanceService.ToJalali(e),StartAt=s,EndAt=e,Description=description?.Trim(),IsOpen=true});await db.SaveChangesAsync();TempData["Result"]="دوره ارزیابی با موفقیت ایجاد شد.";}}catch(ArgumentException ex){TempData["Error"]=ex.Message;}return RedirectToAction(nameof(Periods));
}
[HttpGet] public async Task<IActionResult>ExportPeriods(){var rows=await db.Periods.AsNoTracking().OrderByDescending(x=>x.StartAt).ToListAsync();return File(excel.Periods(rows),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","EvaluationPeriods.xlsx");}
public async Task<IActionResult>Employees(string? q){var x=db.Employees.Include(e=>e.Position).Include(e=>e.Unit).AsQueryable();if(!string.IsNullOrWhiteSpace(q)){q=q.Trim();x=x.Where(e=>e.FullName.Contains(q)||e.PersonnelNo.Contains(q)||e.NationalNo.Contains(q));}return View(await x.OrderBy(e=>e.FullName).ToListAsync());}
[HttpGet]public IActionResult ImportEmployees()=>View();
[HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>ImportEmployees(IFormFile file){if(file==null||file.Length==0){TempData["Error"]="فایل Excel انتخاب نشده است.";return RedirectToAction(nameof(ImportEmployees));}try{var rows=excel.ReadEmployees(file.OpenReadStream());var dup=rows.GroupBy(x=>x.PersonnelNo,StringComparer.OrdinalIgnoreCase).Where(g=>g.Count()>1).Select(g=>g.Key).ToList();if(dup.Count>0)TempData["Error"]="کدهای پرسنلی تکراری: "+string.Join(", ",dup);else if(rows.Any(x=>string.IsNullOrWhiteSpace(x.NationalNo)))TempData["Error"]="کد ملی همه کارکنان باید تکمیل باشد.";else{var pos=await db.Positions.ToDictionaryAsync(x=>x.Code);var units=await db.OrgUnits.ToDictionaryAsync(x=>x.Code);var ok=0;foreach(var r in rows){if(!pos.TryGetValue(r.PositionCode,out var p)||!units.TryGetValue(r.UnitCode,out var u))continue;var e=await db.Employees.SingleOrDefaultAsync(x=>x.PersonnelNo==r.PersonnelNo);var isEval=r.Evaluator is "بله" or "1" or "yes" or "true";if(e==null)db.Employees.Add(e=new Employee{PersonnelNo=r.PersonnelNo,NationalNo=r.NationalNo,FullName=r.FullName,PositionId=p.Id,UnitId=u.Id,IsEvaluator=isEval,IsActive=true});else{e.NationalNo=r.NationalNo;e.FullName=r.FullName;e.PositionId=p.Id;e.UnitId=u.Id;e.IsEvaluator=isEval;e.IsActive=true;}ok++;}await db.SaveChangesAsync();var all=await db.Employees.ToListAsync();foreach(var r in rows){var e=all.FirstOrDefault(x=>x.PersonnelNo==r.PersonnelNo);if(e!=null)e.SupervisorId=all.FirstOrDefault(x=>x.PersonnelNo==r.SupervisorPersonnelNo)?.Id;}foreach(var e in all.Where(x=>x.IsActive)){var u=await db.Users.SingleOrDefaultAsync(x=>x.UserName==e.PersonnelNo);if(u==null)db.Users.Add(new AppUser{UserName=e.PersonnelNo,DisplayName=e.FullName,EmployeeId=e.Id,PasswordHash=PasswordHasher.Hash(e.NationalNo),IsActive=true});else{u.EmployeeId=e.Id;u.DisplayName=e.FullName;u.IsActive=true;u.IsAdmin=false;if(string.IsNullOrWhiteSpace(u.PasswordHash))u.PasswordHash=PasswordHasher.Hash(e.NationalNo);}}await db.SaveChangesAsync();TempData["Result"]=$"{ok} رکورد پردازش شد و حساب ورود کارکنان ایجاد یا به‌روزرسانی شد.";}}catch{TempData["Error"]="ساختار یا محتوای فایل Excel قابل پردازش نیست.";}return RedirectToAction(nameof(Employees));}
[HttpGet]public async Task<IActionResult>ExportEmployees(){var rows=await db.Employees.Include(x=>x.Position).Include(x=>x.Unit).ToListAsync();return File(excel.Employees(rows),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Employees.xlsx");}
}