using System.Security.Claims;
using Indamin.Performance.Data;
using Indamin.Performance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Indamin.Performance.Controllers;
[Authorize]
public class EvaluationController(AppDbContext db,PerformanceService ps,ExcelService excel):Controller
{
 public async Task<IActionResult>Index(){if(!int.TryParse(User.FindFirstValue("EmployeeId"),out var evaluatorId)||!await ps.IsEvaluator(evaluatorId))return Forbid();var period=await ps.LatestStartedPeriod();if(period==null)return View(new List<Row>());var employees=await ps.GetSubordinates(evaluatorId);var ids=employees.Select(x=>x.Id).ToList();var evs=await db.Evaluations.AsNoTracking().Where(x=>x.PeriodId==period.Id&&ids.Contains(x.EmployeeId)).ToListAsync();var evalIds=evs.Select(x=>x.EvaluatorId).Distinct().ToList();var names=await db.Employees.Where(x=>evalIds.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,x=>x.FullName);var rows=employees.Select(e=>{var ev=evs.FirstOrDefault(x=>x.EmployeeId==e.Id);var max=ev?.FinalMaxScore??0;var score=ev?.FinalScore??0;return new Row(e.Id,e.FullName,e.PersonnelNo,e.Position?.Title??"—",e.Unit?.Title??"—",e.IsEvaluator,ev?.Status.ToString()??"ثبت نشده",score,max,max>0?Math.Round(score*100/max,1):0,ev==null?"—":names.GetValueOrDefault(ev.EvaluatorId,"—"),ev!=null&&ev.EvaluatorId!=evaluatorId);}).ToList();ViewBag.Period=period;return View(rows);}
 [HttpGet]public async Task<IActionResult>ExportMyList(){if(!int.TryParse(User.FindFirstValue("EmployeeId"),out var eid)||!await ps.IsEvaluator(eid))return Forbid();return File(excel.Employees(await ps.GetSubordinates(eid)),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","MySubordinates.xlsx");}
 [HttpGet]public async Task<IActionResult>Form(int id){if(!int.TryParse(User.FindFirstValue("EmployeeId"),out var actor)||!await ps.IsEvaluator(actor))return Forbid();var period=await ps.LatestStartedPeriod();if(period==null)return NotFound("دوره‌ای تعریف نشده است.");var employee=await db.Employees.AsNoTracking().Include(x=>x.Position).SingleOrDefaultAsync(x=>x.Id==id&&x.IsActive);if(employee==null||!await ps.CanEvaluate(actor,id))return Forbid();var ev=await db.Evaluations.Include(x=>x.Scores).SingleOrDefaultAsync(x=>x.PeriodId==period.Id&&x.EmployeeId==id);var qs=await QuestionList(employee.PositionId);var history=ev==null?[]:await History(ev.Id);if(ev==null&&!await ps.CanEdit(period))return View(new FormVm(period,employee,qs,null,false,"برای این دوره هنوز ارزیابی ثبت نشده و بازه ثبت نیز پایان یافته است.",history,0,0));var review=true;if(ev is not null)review=await ps.CanReviewEvaluation(actor,ev);var edit=await ps.CanEdit(period)&&review;var notice=!await ps.CanEdit(period)?"بازه ارزیابی پایان یافته است؛ اطلاعات فقط قابل مشاهده است.":(!review?"این ارزیابی توسط ارزیاب بالادست بازنگری شده و شما فقط مجاز به مشاهده هستید.":null);var viewQs=qs.Select(q=>q with {Score=ev.Scores.FirstOrDefault(s=>s.QuestionId==q.QuestionId)?.Score??0,Comment=ev.Scores.FirstOrDefault(s=>s.QuestionId==q.QuestionId)?.Comment}).ToList();return View(new FormVm(period,employee,viewQs,ev,edit,notice,history,ev.FinalScore,ev.FinalMaxScore));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Form(FormPost m){if(!int.TryParse(User.FindFirstValue("EmployeeId"),out var actor)||!await ps.IsEvaluator(actor))return Forbid();var period=await ps.CurrentPeriod();if(period==null)return BadRequest("در حال حاضر بازه فعالی برای ثبت ارزیابی وجود ندارد.");var employee=await db.Employees.Include(x=>x.Position).SingleOrDefaultAsync(x=>x.Id==m.EmployeeId&&x.IsActive);if(employee==null||!await ps.CanEvaluate(actor,employee.Id))return Forbid();var ev=await db.Evaluations.Include(x=>x.Scores).SingleOrDefaultAsync(x=>x.PeriodId==period.Id&&x.EmployeeId==employee.Id);var isNew=ev==null;if(!isNew&&!await ps.CanReviewEvaluation(actor,ev!))return Forbid();var qs=await QuestionList(employee.PositionId);if(isNew){ev=new Evaluation{PeriodId=period.Id,EmployeeId=employee.Id,EvaluatorId=actor,OriginalEvaluatorId=actor,Status=EvaluationStatus.Draft};foreach(var q in qs){var score=m.Scores.GetValueOrDefault(q.QuestionId);if(score<0||score>q.MaxScore)ModelState.AddModelError($"Scores[{q.QuestionId}]",$"امتیاز «{q.Title}» باید بین صفر و {q.MaxScore} باشد.");ev.Scores.Add(new EvaluationScore{QuestionId=q.QuestionId,Score=score,MaxScore=q.MaxScore,Comment=m.Comments.GetValueOrDefault(q.QuestionId)?.Trim()});}db.Evaluations.Add(ev);}else{foreach(var q in qs){var old=ev!.Scores.FirstOrDefault(x=>x.QuestionId==q.QuestionId);if(old==null){var score=m.Scores.GetValueOrDefault(q.QuestionId);if(score<0||score>q.MaxScore)ModelState.AddModelError($"Scores[{q.QuestionId}]",$"امتیاز «{q.Title}» باید بین صفر و {q.MaxScore} باشد.");ev.Scores.Add(new EvaluationScore{QuestionId=q.QuestionId,Score=score,MaxScore=q.MaxScore,Comment=m.Comments.GetValueOrDefault(q.QuestionId)?.Trim()});continue;}var newScore=m.Scores.GetValueOrDefault(q.QuestionId,old.Score);if(newScore<0||newScore>old.MaxScore)ModelState.AddModelError($"Scores[{q.QuestionId}]",$"امتیاز «{q.Title}» باید بین صفر و {old.MaxScore} باشد.");var comment=m.Comments.GetValueOrDefault(q.QuestionId)?.Trim();if(old.Score!=newScore||old.Comment!=comment){db.ScoreHistory.Add(new EvaluationScoreHistory{EvaluationId=ev.Id,QuestionId=q.QuestionId,OldScore=old.Score,NewScore=newScore,ChangedBy=actor,Reason=ev.EvaluatorId==actor?"اصلاح ارزیابی":"بازنگری ارزیاب بالادست"});old.Score=newScore;old.Comment=comment;old.UpdatedAt=DateTime.UtcNow;}}}
if(!ModelState.IsValid){var posted=qs.Select(q=>q with {Score=m.Scores.GetValueOrDefault(q.QuestionId),Comment=m.Comments.GetValueOrDefault(q.QuestionId)}).ToList();return View(new FormVm(period,employee,posted,ev,true,"برخی امتیازها نامعتبر هستند؛ سقف سؤال را رعایت کنید.",ev!.Id==0?[]:await History(ev.Id),ev.Scores.Sum(x=>x.Score),ev.Scores.Sum(x=>x.MaxScore)));}
if(ev!.EvaluatorId!=actor){db.EvaluatorHistory.Add(new EvaluatorChangeHistory{EvaluationId=ev.Id,PreviousEvaluatorId=ev.EvaluatorId,NewEvaluatorId=actor,ChangedBy=actor,Reason="بازنگری ارزیاب بالادست"});ev.EvaluatorId=actor;}ev.FinalScore=ev.Scores.Sum(x=>x.Score);ev.FinalMaxScore=ev.Scores.Sum(x=>x.MaxScore);ev.Status=EvaluationStatus.Submitted;ev.UpdatedAt=DateTime.UtcNow;var userId=int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var uid)?uid:(int?)null;db.AuditLogs.Add(new AuditLog{Action=isNew?"EvaluationCreated":"EvaluationUpdated",Entity="Evaluation",EntityId=ev.Id.ToString(),Details=$"EmployeeId={employee.Id};EvaluatorId={actor};FinalScore={ev.FinalScore};FinalMaxScore={ev.FinalMaxScore}",UserId=userId});await db.SaveChangesAsync();TempData["Result"]="ارزیابی با موفقیت ثبت و امتیاز نهایی محاسبه شد.";return RedirectToAction(nameof(Index));}
 private Task<List<EvalQuestionVm>>QuestionList(int positionId)=>db.PositionQuestions.AsNoTracking().Where(x=>x.PositionId==positionId&&x.IsActive&&x.Question!=null&&x.Question.IsActive).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Id).Select(x=>new EvalQuestionVm(x.QuestionId,x.Question!.Code,x.Question.Title,x.Question.Domain,x.Question.Description,x.MaxScore,x.SortOrder,0,null)).ToListAsync();
 private Task<List<HistoryRow>>History(int id)=>db.ScoreHistory.AsNoTracking().Where(x=>x.EvaluationId==id).Join(db.Questions,h=>h.QuestionId,q=>q.Id,(h,q)=>new HistoryRow(q.Title,h.OldScore,h.NewScore,h.ChangedBy,h.ChangedAt,h.Reason)).OrderByDescending(x=>x.ChangedAt).ToListAsync();
 public record EvalQuestionVm(int QuestionId,string Code,string Title,string Domain,string? Description,decimal MaxScore,int SortOrder,decimal Score,string? Comment);
 public record FormVm(EvaluationPeriod Period,Employee Employee,List<EvalQuestionVm> Questions,Evaluation? Evaluation,bool CanEdit,string? Notice,List<HistoryRow> History,decimal FinalScore,decimal FinalMaxScore);
 public record HistoryRow(string QuestionTitle,decimal OldScore,decimal NewScore,int ChangedBy,DateTime ChangedAt,string Reason);
 public class FormPost{public int EmployeeId{get;set;}public Dictionary<int,decimal> Scores{get;set;}=[];public Dictionary<int,string> Comments{get;set;}=[];}
 public record Row(int Id,string Name,string PersonnelNo,string Position,string Unit,bool IsEvaluator,string Status,decimal Total,decimal Max,decimal Percentage,string CurrentEvaluator,bool IsTakeover);
}