using Indamin.Performance.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Indamin.Performance.Controllers;
[Authorize(Policy="AdminOnly")]
public class SetupController(AppDbContext db):Controller
{
 public async Task<IActionResult> Positions()=>View(await db.Positions.Include(x=>x.QuestionMappings).ThenInclude(x=>x.Question).OrderBy(x=>x.Title).ToListAsync());
 public async Task<IActionResult> Questions()=>View(new QuestionsVm(await db.Questions.Include(x=>x.PositionMappings).ThenInclude(x=>x.Position).OrderBy(x=>x.Domain).ThenBy(x=>x.Title).ToListAsync(),await db.Positions.Where(x=>x.IsActive).OrderBy(x=>x.Title).ToListAsync()));
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>AddPosition(string code,string title){code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title=="")TempData["Error"]="کد و عنوان رده پستی الزامی است.";else if(await db.Positions.AnyAsync(x=>x.Code==code))TempData["Error"]="کد رده پستی تکراری است.";else{db.Positions.Add(new Position{Code=code,Title=title,MaxScore=0});await db.SaveChangesAsync();TempData["Result"]="رده پستی با موفقیت ایجاد شد.";}return RedirectToAction(nameof(Positions));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>AddQuestion(string code,string title,string domain,string? description){code=code?.Trim()??"";title=title?.Trim()??"";domain=domain?.Trim()??"";if(code==""||title==""||domain=="")TempData["Error"]="کد، عنوان و حوزه ارزیابی سؤال الزامی است.";else if(await db.Questions.AnyAsync(x=>x.Code==code))TempData["Error"]="کد سؤال تکراری است.";else{db.Questions.Add(new Question{Code=code,Title=title,Text=title,Domain=domain,Description=description?.Trim()});await db.SaveChangesAsync();TempData["Result"]="سؤال با موفقیت ایجاد شد.";}return RedirectToAction(nameof(Questions));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>AssignQuestion(int questionId,int positionId,decimal maxScore,int sortOrder=1){var q=await db.Questions.FindAsync(questionId);var p=await db.Positions.FindAsync(positionId);if(q==null||p==null)TempData["Error"]="سؤال یا رده پستی معتبر نیست.";else if(!q.IsActive||!p.IsActive)TempData["Error"]="سؤال یا رده پستی غیرفعال است.";else if(maxScore<=0)TempData["Error"]="سقف امتیاز باید بیشتر از صفر باشد.";else{var map=await db.PositionQuestions.SingleOrDefaultAsync(x=>x.QuestionId==questionId&&x.PositionId==positionId);if(map==null)db.PositionQuestions.Add(new PositionQuestion{QuestionId=questionId,PositionId=positionId,MaxScore=maxScore,SortOrder=Math.Max(1,sortOrder)});else{map.MaxScore=maxScore;map.SortOrder=Math.Max(1,sortOrder);map.IsActive=true;}await db.SaveChangesAsync();p.MaxScore=await db.PositionQuestions.Where(x=>x.PositionId==positionId&&x.IsActive).SumAsync(x=>x.MaxScore);await db.SaveChangesAsync();TempData["Result"]="سؤال با موفقیت به رده پستی متصل شد.";}return RedirectToAction(nameof(Questions));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>RemoveQuestion(int mappingId){var map=await db.PositionQuestions.Include(x=>x.Position).SingleOrDefaultAsync(x=>x.Id==mappingId);if(map==null)TempData["Error"]="اتصال پیدا نشد.";else{map.IsActive=false;await db.SaveChangesAsync();map.Position!.MaxScore=await db.PositionQuestions.Where(x=>x.PositionId==map.PositionId&&x.IsActive).SumAsync(x=>x.MaxScore);await db.SaveChangesAsync();TempData["Result"]="اتصال سؤال حذف شد.";}return RedirectToAction(nameof(Questions));}
 public async Task<IActionResult>OrgUnits()=>View(new OrgUnitsVm(await db.OrgUnits.OrderBy(x=>x.Title).ToListAsync(),await db.OrgUnits.Where(x=>x.IsActive).OrderBy(x=>x.Title).ToListAsync()));
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>AddOrgUnit(string code,string title,int? parentId){code=code?.Trim()??"";title=title?.Trim()??"";if(code==""||title=="")TempData["Error"]="کد و عنوان واحد الزامی است.";else if(await db.OrgUnits.AnyAsync(x=>x.Code==code))TempData["Error"]="کد واحد تکراری است.";else if(parentId.HasValue&&parentId.Value==0)parentId=null;else if(parentId.HasValue&&!await db.OrgUnits.AnyAsync(x=>x.Id==parentId.Value&&x.IsActive))TempData["Error"]="واحد والد معتبر نیست.";else{db.OrgUnits.Add(new OrgUnit{Code=code,Title=title,ParentId=parentId});await db.SaveChangesAsync();TempData["Result"]="واحد سازمانی با موفقیت ایجاد شد.";}return RedirectToAction(nameof(OrgUnits));}
 public record QuestionsVm(List<Question> Questions,List<Position> Positions);public record OrgUnitsVm(List<OrgUnit> Units,List<OrgUnit> ParentOptions);
}