using ClosedXML.Excel;
using Indamin.Performance.Data;
namespace Indamin.Performance.Services;
public class ExcelService
{
    public List<EmployeeImportRow> ReadEmployees(Stream stream){using var wb=new XLWorkbook(stream);var ws=wb.Worksheet(1);var list=new List<EmployeeImportRow>();foreach(var r in ws.RowsUsed().Skip(1)){var no=r.Cell(1).GetString().Trim();if(string.IsNullOrWhiteSpace(no))continue;list.Add(new EmployeeImportRow(no,r.Cell(2).GetString().Trim(),r.Cell(3).GetString().Trim(),r.Cell(4).GetString().Trim(),r.Cell(5).GetString().Trim(),r.Cell(6).GetString().Trim(),r.Cell(7).GetString().Trim()));}return list;}
    public byte[] Employees(IEnumerable<Employee> rows){var items=rows.ToList();using var wb=new XLWorkbook();var ws=wb.Worksheets.Add("کارکنان");var h=new[]{"کد پرسنلی","کد ملی","نام و نام خانوادگی","کد رده پستی","کد واحد","ارزیاب؟","کد پرسنلی سرپرست"};for(var i=0;i<h.Length;i++)ws.Cell(1,i+1).Value=h[i];var r=2;foreach(var e in items){ws.Cell(r,1).Value=e.PersonnelNo;ws.Cell(r,2).Value=e.NationalNo??"";ws.Cell(r,3).Value=e.FullName;ws.Cell(r,4).Value=e.Position?.Code??"";ws.Cell(r,5).Value=e.Unit?.Code??"";ws.Cell(r,6).Value=e.IsEvaluator?"بله":"خیر";var supervisor=items.FirstOrDefault(x=>x.Id==e.SupervisorId);ws.Cell(r,7).Value=supervisor?.PersonnelNo??"";r++;}ws.RangeUsed()?.SetAutoFilter();ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return ms.ToArray();}
    public byte[] Periods(IEnumerable<EvaluationPeriod> rows){var items=rows.ToList();using var wb=new XLWorkbook();var ws=wb.Worksheets.Add("دوره‌ها");var h=new[]{"عنوان","شروع","پایان","وضعیت","توضیحات"};for(var i=0;i<h.Length;i++)ws.Cell(1,i+1).Value=h[i];var r=2;foreach(var x in items){ws.Cell(r,1).Value=x.Title;ws.Cell(r,2).Value=x.StartJalali;ws.Cell(r,3).Value=x.EndJalali;ws.Cell(r,4).Value=x.IsOpen?"باز":"بسته";ws.Cell(r,5).Value=x.Description??"";r++;}ws.RangeUsed()?.SetAutoFilter();ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return ms.ToArray();}
    public byte[] OrgUnits(IEnumerable<OrgUnit> rows){var items=rows.ToList();using var wb=new XLWorkbook();var ws=wb.Worksheets.Add("ساختار سازمانی");var h=new[]{"کد","عنوان","والد","وضعیت"};for(var i=0;i<h.Length;i++)ws.Cell(1,i+1).Value=h[i];var r=2;foreach(var x in items){ws.Cell(r,1).Value=x.Code;ws.Cell(r,2).Value=x.Title;var p=items.FirstOrDefault(y=>y.Id==x.ParentId);ws.Cell(r,3).Value=p?.Title??"سطح اصلی";ws.Cell(r,4).Value=x.IsActive?"فعال":"غیرفعال";r++;}ws.RangeUsed()?.SetAutoFilter();ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return ms.ToArray();}
    public byte[] Positions(IEnumerable<Position> rows){var items=rows.ToList();using var wb=new XLWorkbook();var ws=wb.Worksheets.Add("رده‌های پستی");var h=new[]{"کد","عنوان","سقف کل","تعداد سؤال","وضعیت"};for(var i=0;i<h.Length;i++)ws.Cell(1,i+1).Value=h[i];var r=2;foreach(var x in items){ws.Cell(r,1).Value=x.Code;ws.Cell(r,2).Value=x.Title;ws.Cell(r,3).Value=x.MaxScore;ws.Cell(r,4).Value=x.QuestionMappings.Count(y=>y.IsActive);ws.Cell(r,5).Value=x.IsActive?"فعال":"غیرفعال";r++;}ws.RangeUsed()?.SetAutoFilter();ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return ms.ToArray();}
    public byte[] Questions(IEnumerable<Question> rows){var items=rows.ToList();using var wb=new XLWorkbook();var ws=wb.Worksheets.Add("سؤالات");var h=new[]{"کد","عنوان","متن سؤال","حوزه","توضیحات","تعداد اتصال","وضعیت"};for(var i=0;i<h.Length;i++)ws.Cell(1,i+1).Value=h[i];var r=2;foreach(var x in items){ws.Cell(r,1).Value=x.Code;ws.Cell(r,2).Value=x.Title;ws.Cell(r,3).Value=x.Text;ws.Cell(r,4).Value=x.Domain;ws.Cell(r,5).Value=x.Description??"";ws.Cell(r,6).Value=x.PositionMappings.Count(y=>y.IsActive);ws.Cell(r,7).Value=x.IsActive?"فعال":"غیرفعال";r++;}ws.RangeUsed()?.SetAutoFilter();ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return ms.ToArray();}
    public byte[] Evaluations(IEnumerable<(string Employee,string Evaluator,string Unit,string Position,decimal Score,decimal Max,string Status)> rows){var items=rows.ToList();using var wb=new XLWorkbook();var ws=wb.Worksheets.Add("گزارش ارزیابی");var h=new[]{"کارمند","ارزیاب","واحد","رده پستی","امتیاز","سقف","درصد","وضعیت"};for(var i=0;i<h.Length;i++)ws.Cell(1,i+1).Value=h[i];var r=2;foreach(var x in items){ws.Cell(r,1).Value=x.Employee;ws.Cell(r,2).Value=x.Evaluator;ws.Cell(r,3).Value=x.Unit;ws.Cell(r,4).Value=x.Position;ws.Cell(r,5).Value=x.Score;ws.Cell(r,6).Value=x.Max;ws.Cell(r,7).Value=x.Max==0?0:Math.Round(x.Score/x.Max*100,2);ws.Cell(r,8).Value=x.Status;r++;}ws.RangeUsed()?.SetAutoFilter();ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return ms.ToArray();}
}
public record EmployeeImportRow(string PersonnelNo,string NationalNo,string FullName,string PositionCode,string UnitCode,string Evaluator,string SupervisorPersonnelNo);